---
wireguard_host: 127.0.0.1
wireguard_privatekey_host: IKJPGZNOcrbIh1QU8yJ6oaXsSyUoQp8QUhm1uvfp5Vo=
wireguard_privatekey_peer: EKgPYhHgk1kqIkR+kFCvU8+N+yiLwqDkjcl0cy1vs2Y=
wireguard_publickey_host: 7I3L6nZ0P3K6TmWzJUe3xQjk/gTyoNaCwe1oDHpfGGI=
wireguard_publickey_peer: iEuV0dLE9OYfZzoKYrHZBK6Hzr/8dn1aovDuUrt9/g8=
