---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: deadnews.util.system_info
    - role: deadnews.util.docker
      docker_rootless: true
      docker_rootless_expose_privileged_ports: true
      docker_cleanup_scheduled: true
      docker_hold_packages: true
