---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Test role
      ansible.builtin.import_role:
        name: deadnews.util.docker
      vars:
        docker_rootless: true
        docker_rootless_expose_privileged_ports: true
        docker_cleanup_scheduled: true
        docker_hold_packages: true
