---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: debian12
    box: debian/bookworm64
    config_options:
      vm.boot_timeout: 600
    memory: 1024

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
