---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: deadnews.util.docker

    - name: Deploy Docker App
      ansible.builtin.import_role:
        name: deadnews.util.docker_compose
      vars:
        docker_compose_project: docker-app
        docker_compose_target_dir: ~/docker-compose
        docker_compose_files:
          - src: files/.env
          - src: files/docker-compose.yml
            validate: docker compose -f %s config
          - src: templates/.env.dev.j2
            dest: .env.dev-dev
            mode: "0644"
        docker_compose_containers_check:
          - docker-app

    - name: Verify that Docker App is responding
      ansible.builtin.uri:
        url: http://127.0.0.1:8000/health
      register: docker_app_verify
      retries: 5
      delay: 8
      until: docker_app_verify is not failed
