---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: deadnews.util.docker

    - name: Deploy Docker App
      ansible.builtin.import_role:
        name: deadnews.util.docker_compose
      vars:
        docker_compose_project: docker-app
        docker_compose_target_dir: ~/docker-compose
        docker_compose_source: files/docker-compose.yml
        docker_compose_env: files/.env

    - name: Verify that Docker App is responding
      ansible.builtin.uri:
        url: http://127.0.0.1:9000/health
      register: docker_app_verify
      retries: 5
      delay: 8
      until: docker_app_verify is not failed
