---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Show system info
      ansible.builtin.import_role:
        name: deadnews.util.system_info

    - name: Install Docker
      ansible.builtin.import_role:
        name: deadnews.util.docker

    - name: Deploy Docker App
      ansible.builtin.import_role:
        name: deadnews.util.docker_compose
      vars:
        docker_compose_project: docker-app
        docker_compose_target_dir: ~/docker-compose
        docker_compose_state: present
        docker_compose_files:
          - src: files/docker-compose.yml
          - src: files/.env
          - src: templates/.env.dev.j2
            dest: .env.dev-dev
            mode: "0644"
        docker_compose_files_show: true
        docker_compose_sleep_time: 1
        docker_compose_logs: true
        docker_compose_containers_exec:
          - container: docker-app
            cmd: ls -lha /
          - container: docker-app
            cmd: echo "Hello, World!"
        docker_compose_containers_logs: [docker-app]
        docker_compose_containers_check: [docker-app]

    - name: Verify that Docker App is responding
      ansible.builtin.uri:
        url: http://127.0.0.1:8000/health
      register: docker_app_verify
      retries: 12
      delay: 5
      until: docker_app_verify is not failed
