---
driver:
  name: docker

platforms:
  - name: ${MOLECULE_DISTRO:-debian12}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: ../../../../molecule/playbooks/prepare-systemd.yml
  env:
    ANSIBLE_VERBOSITY: 0
