---
argument_specs:
  main:
    short_description: The main entry point for the docker_compose role.
    options:
      docker_compose_project:
        type: str
        required: true
        description: The name of Docker Compose project which should be deployed.

      docker_compose_target_dir:
        type: str
        required: true
        description: The directory where the Docker Compose project directory should be created.

      docker_compose_copy:
        type: list
        elements: dict
        required: false
        description: A list of files to copy to the Docker Compose project directory.
        options:
          src:
            type: str
            required: true
            description: The source file to copy.
          dest:
            type: str
            required: true
            description: |
              The destination where the file will be copied.
              Relative to the Docker Compose project directory.

      docker_compose_template:
        type: list
        elements: dict
        required: false
        description: A list of templates to render to the Docker Compose project directory.
        options:
          src:
            type: str
            required: true
            description: The jinja2 template to render.
          dest:
            type: str
            required: true
            description: |
              The destination where the template will be rendered.
              Relative to the Docker Compose project directory.
