---
argument_specs:
  main:
    short_description: The main entry point for the docker_compose role.
    options:
      docker_compose_project:
        type: str
        required: true
        description: The name of Docker Compose project which should be deployed.

      docker_compose_target_dir:
        type: str
        required: true
        description: The directory where the Docker Compose project directory should be created.

      docker_compose_files:
        type: list
        elements: dict
        required: true
        description: A list of files to create in the Docker Compose project directory.
        options:
          src:
            type: str
            required: true
            description: |
              The source file to copy.
              Or the jinja2 template to render.
          dest:
            type: str
            required: false
            description: |
              The destination where the file will be created.
              Relative to the Docker Compose project directory.
              By default, the destination is the same as the source filename, with .j2 extension stripped.
          mode:
            type: str
            required: false
            default: "0600"
            description: The file mode to set on the created file.
          validate:
            type: str
            required: false
            description: The validation command to run before copying the updated file into the final destination.

      docker_compose_containers_check:
        type: list
        elements: str
        required: false
        description: A list of container names to assert are running after the Docker Compose project is deployed.
