---
argument_specs:
  main:
    short_description: The main entry point for the docker_compose role.
    options:
      docker_compose_state:
        type: str
        default: present
        description: The state of the Docker Compose project.
        choices:
          - present
          - absent

      docker_compose_project:
        type: str
        required: true
        description: The name of Docker Compose project which should be deployed.

      docker_compose_target_dir:
        type: str
        required: true
        description: The directory where the Docker Compose project directory should be created.

      docker_compose_files:
        type: list
        elements: dict
        required: false # true if docker_compose_state == present
        description: A list of files to create in the Docker Compose project directory.
        options:
          src:
            type: str
            required: true
            description: |
              The source file to copy.
              Or the jinja2 template to render.
          dest:
            type: str
            required: false
            description: |
              The destination where the file will be created.
              Relative to the Docker Compose project directory.
              By default, the destination is the same as the source filename, with .j2 extension stripped.
          mode:
            type: str
            required: false
            default: "0600"
            description: The file mode to set on the created file.
          directory_mode:
            type: str
            required: false
            default: "0700"
            description: |
              The directory mode to set on the created directory.
              See the directory_mode option in the ansible.builtin.copy module for more details.
          validate:
            type: str
            required: false
            description: The validation command to run before copying the updated file into the final destination.

      docker_compose_files_show:
        type: bool
        required: false
        description: Whether to show the files in the Docker Compose project after they are created.

      docker_compose_sleep_time:
        type: int
        required: false
        description: The number of seconds to sleep after the Docker Compose project is deployed.

      docker_compose_logs:
        type: bool
        required: false
        description: Whether to show logs for the Docker Compose project after it is deployed.

      docker_compose_containers_exec:
        type: list
        elements: dict
        required: false
        description: A list of containers to execute commands in after the Docker Compose project is deployed.
        options:
          container:
            type: str
            required: true
            description: The name of the container to execute the command in.
          cmd:
            type: str
            required: true
            description: The command to execute in the container.

      docker_compose_containers_logs:
        type: list
        elements: str
        required: false
        description: A list of container names to show logs for after the Docker Compose project is deployed.

      docker_compose_containers_check:
        type: list
        elements: str
        required: false
        description: |
          A list of container names to assert are running after the Docker Compose project is deployed.
          If containers health checks are defined, they will be used to determine if the container is healthy.
