---
- name: (Handler) Restart rootless docker.service
  become: true
  become_user: "{{ docker_rootless_user }}"
  become_flags: --login
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: "{{ true if docker_config_daemon is defined else false }}"
    scope: user

- name: (Handler) Restart system docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: "{{ true if docker_config_daemon is defined else false }}"
    scope: system
