---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: deadnews.util.system_info
    - role: deadnews.util.aptup
      aptup_next_release: true
      aptup_show_stdout: true
      aptup_next_release_update_grub: false
