---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: deadnews.util.system_info
    - role: deadnews.util.docker
      docker_rootless: true
      docker_config: files/config.json
      docker_config_daemon: files/daemon.json
      docker_config_systemd: templates/proxy.conf.j2
