---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Test role
      ansible.builtin.import_role:
        name: deadnews.util.docker
      vars:
        docker_rootless: false
        docker_config: files/docker-config.json
