---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: deadnews.util.docker
      vars:
        docker_rootless: false
        docker_config: files/config.json
        docker_config_daemon: files/daemon.json
