---
# Replace the codename to next LTS version

- name: Debian 10 to 11
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: buster
    replace: bullseye
  when:
    - ansible_distribution == 'Debian'
    - ansible_lsb.major_release | int == 10

- name: Debian 11 to 12
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: bullseye
    replace: bookworm
  when:
    - ansible_distribution == 'Debian'
    - ansible_lsb.major_release | int == 11

- name: Ubuntu 18 to 20
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: bionic
    replace: focal
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_lsb.major_release | int == 18

- name: Ubuntu 20 to 22
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: focal
    replace: jammy
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_lsb.major_release | int == 20

- name: Ubuntu 22 to 24
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: jammy
    replace: noble
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_lsb.major_release | int == 22
