---
# Upgrade Debian-based OS

- name: Check distribution compatibility
  ansible.builtin.assert:
    that:
      - ansible_os_family is defined
      - ansible_os_family == 'Debian'

- name: Upgrade Debian-based OS
  ansible.builtin.import_role:
    name: deadnews.util.aptup
    tasks_from: upgrade

- name: Upgrade Debian-based OS from one LTS to the next LTS
  ansible.builtin.include_role:
    name: deadnews.util.aptup
    tasks_from: next_release
  when:
    - aptup_next_release is defined
    - aptup_next_release
