---
# Upgrade Debian-based OS

- name: Check distribution compatibility
  ansible.builtin.assert:
    that:
      - ansible_os_family is defined
      - ansible_os_family == 'Debian'

- name: Upgrade Debian-based OS
  ansible.builtin.import_role:
    name: deadnews.util.aptup
    tasks_from: upgrade

- name: Upgrade Debian-based OS from one LTS to the next LTS
  when: aptup_next_release
  ansible.builtin.include_role:
    name: deadnews.util.aptup
    tasks_from: next_release

- name: Clean up apt cache and remove unused packages
  when: aptup_cleanup
  block:
    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: true

    - name: Clean apt cache
      ansible.builtin.apt:
        clean: true
