---
# Upgrade Debian-based OS from one LTS to the next LTS

- name: Replace the codename to next LTS version
  ansible.builtin.import_role:
    name: deadnews.util.aptup
    tasks_from: codenames

- name: Upgrade the OS (apt full-upgrade)
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    dpkg_options: force-confold,force-confdef
    autoremove: true
    allow_change_held_packages: true
  register: aptup_full
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: "{{ 'a' if aptup_restart_services else 'l' }}"

- name: Show full-upgrade result
  ansible.builtin.debug:
    var: aptup_full.stdout
  when:
    - aptup_show_stdout is defined
    - aptup_show_stdout

- name: Invalidate facts cache
  ansible.builtin.meta: clear_facts

- name: Update facts about remote host
  ansible.builtin.setup:

- name: Make sure that the GRUB is updated
  ansible.builtin.command:
    cmd: update-grub
  changed_when: true
  when:
    - aptup_next_release_update_grub is defined
    - aptup_next_release_update_grub
