---
services:
  docker_app:
    image: ghcr.io/deadnews/deadnews-template-python:2.0.11@sha256:70b53f610278f4d6e3306db3b311b68325cca027592585893833fd493fdcdf27
    container_name: docker-app
    restart: on-failure:2
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${UVICORN_PORT}/health || exit 1
      interval: 60s
      retries: 3
      timeout: 10s
      start_period: 60s
    ports:
      - 127.0.0.1:${UVICORN_PORT}:${UVICORN_PORT}
    environment:
      UVICORN_PORT: ${UVICORN_PORT}
