---
services:
  docker_app:
    image: ghcr.io/deadnews/deadnews-template-python:2.0.10@sha256:9a7f3f07e289174dfd469916efaa578cda09653e443a69a145b0d2b92cb9ccf6
    container_name: docker-app
    restart: on-failure:2
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${UVICORN_PORT}/health || exit 1
      interval: 60s
      retries: 3
      timeout: 10s
      start_period: 60s
    ports:
      - 127.0.0.1:${UVICORN_PORT}:${UVICORN_PORT}
    environment:
      UVICORN_PORT: ${UVICORN_PORT}
