---
services:
  docker_app:
    image: ghcr.io/deadnews/deadnews-template-python:2.0.8@sha256:40380050d71281428d9d3514af152e072a07f1c43152aec37ef9f5f25ae208ba
    container_name: docker-app
    restart: on-failure:2
    ports:
      - 127.0.0.1:${UVICORN_PORT}:${UVICORN_PORT}
    environment:
      UVICORN_PORT: ${UVICORN_PORT}
