---
services:
  docker_app:
    image: ghcr.io/deadnews/deadnews-template-python:2.0.9@sha256:fe4ce49afd409c289cf7b0dc257e63edd6390926a72fabf44c631c3f16d1a6a2
    container_name: docker-app
    restart: on-failure:2
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${UVICORN_PORT}/health || exit 1
      interval: 60s
      retries: 3
      timeout: 10s
      start_period: 60s
    ports:
      - 127.0.0.1:${UVICORN_PORT}:${UVICORN_PORT}
    environment:
      UVICORN_PORT: ${UVICORN_PORT}
