---
- name: (Handler) Down Docker Compose project containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    pull: never
    recreate: never
    state: absent
  register: compose_down
  notify: (Handler) Show actions for docker compose down

- name: (Handler) Show actions for docker compose down
  ansible.builtin.debug:
    var: compose_down.actions
