---
# Deploy Docker Compose projects

- name: Deploy Docker Compose project
  when: docker_compose_state == 'present'
  ansible.builtin.include_tasks:
    file: deploy.yml

- name: Remove Docker Compose project
  when: docker_compose_state == 'absent'
  ansible.builtin.include_tasks:
    file: remove.yml
