---
# Deploy Docker Compose projects (with docker compose v2)

- name: Validate mutually exclusive parameters
  ansible.builtin.assert:
    that:
      - docker_compose_env_template is not defined
    msg: "`docker_compose_env_template` must not be defined when `docker_compose_env` is set."
  when: docker_compose_env is defined

- name: Create directory for Docker Compose project {{ docker_compose_project }}
  ansible.builtin.file:
    path: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    state: directory
    mode: "0700"

- name: Copy Docker Compose project {{ docker_compose_project }}
  ansible.builtin.copy:
    src: "{{ docker_compose_source }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/docker-compose.yml"
    mode: "0600"

- name: Copy additional files for Docker Compose project {{ docker_compose_project }}
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/{{ item.split('/')[-1] }}"
    mode: "0600"
  loop: "{{ docker_compose_copy_files }}"
  when: docker_compose_copy_files is defined

- name: Copy environment file for Docker Compose project {{ docker_compose_project }}
  ansible.builtin.copy:
    src: "{{ docker_compose_env }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/.env"
    mode: "0600"
  when: docker_compose_env is defined

- name: Create environment file for Docker Compose project {{ docker_compose_project }}
  ansible.builtin.template:
    src: "{{ docker_compose_env_template }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/.env"
    mode: "0600"
  when: docker_compose_env_template is defined

- name: Pull images for Docker Compose project {{ docker_compose_project }}
  community.docker.docker_compose_v2_pull:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
  register: pull_output

- name: Show pull results
  ansible.builtin.debug:
    var: pull_output
  when:
    - pull_output.failed
    - or verbosity > 0

- name: Ensure Docker Compose project is up-to-date and running ー {{ docker_compose_project }}
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    pull: never
  register: compose_output

- name: Show compose results
  ansible.builtin.debug:
    var: compose_output
  when:
    - compose_output.failed
    - or verbosity > 0
