---
# Deploy Docker Compose projects (with docker compose v2)

- name: Create directory for the Docker Compose project {{ docker_compose_project }}
  ansible.builtin.file:
    path: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    state: directory
    mode: "0700"

- name: Copy files to the Docker Compose project {{ docker_compose_project }}
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/{{ item.dest }}"
    mode: "0600"
  loop: "{{ docker_compose_copy }}"
  when: docker_compose_copy is defined

- name: Render templates to the Docker Compose project {{ docker_compose_project }}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/{{ item.dest }}"
    mode: "0600"
  loop: "{{ docker_compose_template }}"
  when: docker_compose_template is defined

- name: Pull images for the Docker Compose project {{ docker_compose_project }}
  community.docker.docker_compose_v2_pull:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
  register: pull_output

- name: Show pull results
  ansible.builtin.debug:
    var: pull_output
  when:
    - pull_output.failed
    - or verbosity > 0

- name: Ensure the Docker Compose project is up-to-date and running ー {{ docker_compose_project }}
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    pull: never
  register: compose_output

- name: Show compose results
  ansible.builtin.debug:
    var: compose_output
  when:
    - compose_output.failed
    - or verbosity > 0
