---
# Deploy Docker Compose projects (with docker compose v2)

- name: Create directory for the Docker Compose project {{ docker_compose_project }}
  ansible.builtin.file:
    path: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    state: directory
    mode: "0700"

- name: Create files in the Docker Compose project {{ docker_compose_project }}
  when: docker_compose_files is defined
  block:
    - name: Template files in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/{{ item.dest | default(item.src | basename | split('.j2') | first) }}"
        mode: "{{ item.mode | default('0600') }}"
        validate: "{{ item.validate | default('') }}"
      loop: "{{ docker_compose_files }}"
      notify:
        - (Handler) Restart Docker Compose project containers
      when:
        - item.src.endswith('.j2')

    - name: Copy files in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/{{ item.dest | default(item.src | basename) }}"
        mode: "{{ item.mode | default('0600') }}"
        validate: "{{ item.validate | default('') }}"
      loop: "{{ docker_compose_files }}"
      notify:
        - (Handler) Restart Docker Compose project containers
      when:
        - not item.src.endswith('.j2')

- name: Create the Docker Compose file in the Docker Compose project {{ docker_compose_project }}
  block:
    - name: Template the Docker Compose file in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.template:
        src: "{{ docker_compose_src }}"
        dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/docker-compose.yml"
        mode: "0600"
        validate: docker compose -f %s config
      when:
        - docker_compose_src.endswith('.j2')

    - name: Copy the Docker Compose file in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.copy:
        src: "{{ docker_compose_src }}"
        dest: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/docker-compose.yml"
        mode: "0600"
        validate: docker compose -f %s config
      when:
        - not docker_compose_src.endswith('.j2')

    - name: List files in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.command:
        cmd: ls -lha "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
      changed_when: false
      register: ls_output
      when: ansible_verbosity > 0

    - name: Show files in the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.debug:
        var: ls_output.stdout_lines
        verbosity: 1

    - name: Validate the Docker Compose project {{ docker_compose_project }}
      ansible.builtin.command:
        cmd: docker compose -f "{{ docker_compose_target_dir }}/{{ docker_compose_project }}/docker-compose.yml" config
      changed_when: false
      register: config_output
      when: ansible_verbosity > 0

    - name: Show Docker Compose project validation results
      ansible.builtin.debug:
        var: config_output.stdout_lines
        verbosity: 1

- name: Pull images for the Docker Compose project {{ docker_compose_project }}
  community.docker.docker_compose_v2_pull:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
  register: pull_output

- name: Show pull results
  ansible.builtin.debug:
    var: pull_output
    verbosity: 1

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure the Docker Compose project is up-to-date and running ー {{ docker_compose_project }}
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_target_dir }}/{{ docker_compose_project }}"
    pull: never
    state: present
  register: compose_output

- name: Show compose results
  ansible.builtin.debug:
    var: compose_output
    verbosity: 1

- name: Ensure that Docker containers are running
  when:
    - docker_compose_containers_check is defined
    - docker_compose_containers_check
  block:
    - name: Get Docker container info
      community.docker.docker_container_info:
        name: "{{ item }}"
      register: container_info
      loop: "{{ docker_compose_containers_check }}"

    - name: Show Docker containers info
      ansible.builtin.debug:
        var: container_info
        verbosity: 2

    - name: Assert Docker container is running
      ansible.builtin.assert:
        that: item.container.State.Running
        quiet: true
      loop: "{{ container_info.results }}"
      loop_control:
        label: "{{ item.item }}"
