---
# Schedule Docker images cleanup

- name: Set the cron job user
  ansible.builtin.set_fact:
    job_user: "{{ docker_rootless_user if docker_rootless else 'root' }}"

- name: Create a cron for clear dangling Docker images
  ansible.builtin.cron:
    name: clear dangling Docker images
    special_time: weekly
    user: "{{ job_user }}"
    job: docker image prune -f
    cron_file: docker-image-clear-dangling-{{ job_user }}

- name: Create a cron for clear unused Docker images created more than 3 months ago
  ansible.builtin.cron:
    name: clear unused Docker images created more than 3 months ago
    special_time: monthly
    user: "{{ job_user }}"
    job: docker image prune -f --all --filter "until=2160h"
    cron_file: docker-image-clear-unused-{{ job_user }}
