---
# Create Docker configs

- name: Create directory for the Docker configs
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.docker"
    state: directory
    mode: "0751"

- name: Create the Docker config.json. The config only applies to new containers.
  ansible.builtin.template:
    src: "{{ docker_config }}"
    dest: "{{ ansible_user_dir }}/.docker/config.json"
    mode: "0600"
  when:
    - docker_config is defined

- name: Create the Docker daemon.json
  ansible.builtin.template:
    src: "{{ docker_config_daemon }}"
    dest: "{{ ansible_user_dir }}/.docker/daemon.json"
    mode: "0600"
  notify:
    - (Handler) Restart system docker.service
  when:
    - docker_config_daemon is defined

- name: Create the Docker systemd service config
  when:
    - docker_config_systemd is defined
  block:
    - name: Set the Docker systemd service config directory
      ansible.builtin.set_fact:
        docker_config_systemd_dir: >
          {{
            ansible_user_dir + '/.config/systemd/user/docker.service.d'
            if docker_rootless
            else '/etc/systemd/system/docker.service.d'
          }}

    - name: Create directory for the Docker systemd service configs
      ansible.builtin.file:
        path: "{{ docker_config_systemd_dir }}"
        state: directory
        mode: "0751"

    - name: Create the Docker systemd service config
      ansible.builtin.template:
        src: "{{ docker_config_systemd }}"
        dest: "{{ docker_config_systemd_dir }}/{{ (docker_config_systemd.split('/')[-1]).split('.j2')[0] }}"
        mode: "0600"
      notify:
        - (Handler) Restart system docker.service
