---
# Create Docker configs.
# Should be run as the user that will be running Docker.

- name: Set the Docker user home directory
  ansible.builtin.set_fact:
    docker_user_home: "{{ docker_rootless_user_home if docker_rootless else '/root' }}"

- name: Create directory for the Docker configs
  ansible.builtin.file:
    path: "{{ docker_user_home }}/.docker"
    state: directory
    mode: "0751"

- name: Create the Docker config.json. The config only applies to new containers.
  ansible.builtin.template:
    src: "{{ docker_config }}"
    dest: "{{ docker_user_home }}/.docker/config.json"
    mode: "0600"
  when:
    - docker_config is defined

# TODO: add validation
# TODO: if src extension is .j2, then use `ansible.builtin.template` else use `ansible.builtin.copy`
- name: Create the Docker daemon.json
  ansible.builtin.template:
    src: "{{ docker_config_daemon }}"
    dest: "{{ docker_user_home }}/.docker/daemon.json"
    mode: "0600"
    # validate: dockerd --config-file {{ docker_user_home }}/.docker/daemon.json --validate
  notify:
    - "{{ '(Handler) Restart rootless docker.service' if docker_rootless else '(Handler) Restart system docker.service' }}"
  when:
    - docker_config_daemon is defined

- name: Create the Docker systemd service config
  when:
    - docker_config_systemd is defined
  block:
    - name: Set the Docker systemd service config directory
      ansible.builtin.set_fact:
        docker_config_systemd_dir: >-
          {{
            docker_user_home + '/.config/systemd/user/docker.service.d'
            if docker_rootless
            else '/etc/systemd/system/docker.service.d'
          }}

    - name: Create directory for the Docker systemd service configs
      ansible.builtin.file:
        path: "{{ docker_config_systemd_dir }}"
        state: directory
        mode: "0751"

    - name: Create the Docker systemd service config
      ansible.builtin.template:
        src: "{{ docker_config_systemd }}"
        dest: "{{ docker_config_systemd_dir }}/{{ (docker_config_systemd.split('/')[-1]).split('.j2')[0] }}"
        mode: "0600"
      notify:
        - "{{ '(Handler) Restart rootless docker.service' if docker_rootless else '(Handler) Restart system docker.service' }}"
