---
# Install Docker on Debian-family OS

- name: Install Docker
  ansible.builtin.import_role:
    name: deadnews.util.docker
    tasks_from: install

- name: Install Docker in rootfull mode
  ansible.builtin.include_role:
    name: deadnews.util.docker
    tasks_from: rootfull
  when:
    - docker_rootless is defined
    - not docker_rootless

- name: Install Docker in rootless mode
  ansible.builtin.include_role:
    name: deadnews.util.docker
    tasks_from: rootless
  when:
    - docker_rootless is defined
    - docker_rootless

- name: Schedule Docker images cleanup
  ansible.builtin.include_role:
    name: deadnews.util.docker
    tasks_from: cleanup
  when:
    - docker_cleanup_scheduled is defined
    - docker_cleanup_scheduled
