---
# Install Docker on Debian-family OS

- name: Check distribution compatibility
  ansible.builtin.assert:
    that:
      - ansible_os_family is defined
      - ansible_os_family == 'Debian'

- name: Uninstall Docker packages
  when: docker_uninstall
  ansible.builtin.import_role:
    name: deadnews.util.docker
    tasks_from: uninstall

- name: Install Docker
  when: not docker_uninstall
  block:
    - name: Install Docker
      ansible.builtin.import_role:
        name: deadnews.util.docker
        tasks_from: install

    - name: Setup Docker in rootfull mode
      when: not docker_rootless
      ansible.builtin.include_role:
        name: deadnews.util.docker
        tasks_from: rootfull

    - name: Setup Docker in rootless mode
      when: docker_rootless
      ansible.builtin.include_role:
        name: deadnews.util.docker
        tasks_from: rootless

    - name: Schedule Docker images cleanup
      when: docker_cleanup_scheduled
      ansible.builtin.include_role:
        name: deadnews.util.docker
        tasks_from: cleanup
