---
# Install Docker in rootfull mode

- name: Create Docker configs
  ansible.builtin.import_role:
    name: deadnews.util.docker
    tasks_from: configs

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure that docker.service is started and enabled
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system

- name: Verify that Docker daemon is responding
  ansible.builtin.command:
    cmd: docker info
  changed_when: false
