---
# Install Docker in rootfull mode

- name: Create directory for the Docker config
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    mode: "0700"

# TODO: can be template
- name: Create docker config
  ansible.builtin.copy:
    src: "{{ docker_config }}"
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: "0600"
  when:
    - docker_config is defined
  notify:
    - (Handler) Restart rootfull docker.service

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure that docker.service is started
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system

- name: Verify that Docker daemon is responding
  ansible.builtin.command:
    cmd: docker info
  changed_when: false
