---
# Install Docker in rootfull mode

- name: Ensure that docker.service is started
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system

- name: Verify that Docker daemon is responding
  ansible.builtin.command:
    cmd: docker info
  changed_when: false
