---
# Install Docker in rootfull mode

- name: Create directories for the Docker configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0751"
  loop:
    - /root/.docker
    - /etc/systemd/system/docker.service.d

- name: Create the Docker configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0600"
  notify: "{{ '(Handler) Restart system docker.service' if item.restart else [] }}"
  loop:
    - src: "{{ docker_config }}"
      dest: /root/.docker/config.json
      restart: false
    - src: "{{ docker_config_daemon }}"
      dest: /root/.docker/daemon.json
      restart: true
  # - src: "{{ docker_config_systemd }}"
  #   dest: "/etc/systemd/system/docker.service.d/{{ item.src.split('/')[-1] }}"
  #   restart: true
  when: item.src is defined

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure that docker.service is started and enabled
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system

- name: Verify that Docker daemon is responding
  ansible.builtin.command:
    cmd: docker info
  changed_when: false
