---
# Install Docker in rootfull mode

- name: Create directory for the Docker config
  ansible.builtin.file:
    path: /root/.docker
    state: directory
    mode: "0751"

- name: Create the Docker config
  ansible.builtin.template:
    src: "{{ docker_config }}"
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: "0600"
  notify:
    - (Handler) Restart rootfull docker.service
  when:
    - docker_config is defined

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure that docker.service is started and enabled
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system

- name: Verify that Docker daemon is responding
  ansible.builtin.command:
    cmd: docker info
  changed_when: false
