---
# Uninstall Docker packages

- name: Set Docker packages list
  ansible.builtin.set_fact:
    docker_pkgs:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - docker-compose-plugin

- name: Uninstall and Purge Docker packages
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: absent
    purge: true
    autoremove: true
    allow_change_held_packages: true

- name: Remove Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    architectures: amd64
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: absent
