---
# Default converge playbook for Molecule

- name: Converge
  hosts: all

  tasks:
    - name: Test role
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
